services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ids_user
      POSTGRES_PASSWORD: ids_pass
      POSTGRES_DB: ids_db
    ports:
      - "5432:5432"
    volumes:
      - ids_pg_data:/var/lib/postgresql/data

volumes:
  ids_pg_data:
